### PR TITLE
Fix incorrect order of command execution

### PR DESCRIPTION
**Pull request by zer0big**
Docker Command execution order was wrong, so we fixed it in the correct order.

### CODE REVIEW

**Comment by zer0big** [comment]
@jwendl, @ianisms 
Please review my PR. Thanks in advance.

**Review by jwendl — APPROVED** [review]
Looks good - thank you for the contribution!

**Comment by jwendl** [comment]
Looks like @ianisms is going to have to merge it though - I will let him know.

**Comment by ianisms** [comment]
Looks great thank you for your contribution!

**Pull request merged**
